version: '3.8'
services:
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest # Sesuaikan versi
    container_name: cadvisor
    mounts:
    - type: bind
      source: /
      target: /rootfs
      read_only: true
    
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock
      read_only: true
    
    - type: bind
      source: /run
      target: /run
      read_only: true
    
    - type: bind
      source: /sys
      target: /sys
      read_only: true
    
    - type: bind
      source: /var/lib/docker
      target: /var/lib/docker
      read_only: true
    
    - type: bind
      source: /proc
      target: /proc
      read_only: true

    deploy:
      mode: global

  collector:
    image: ${ACR_URL}/metrics-collector:${IMAGE_TAG}
    container_name: metrics-collector
    environment:
      - CADVISOR_URL=http://cadvisor:8080/api/v1.3/containers/
      - API_URL=https://aca-monitoring-api.politesea-d4b7dfa0.spaincentral.azurecontainerapps.io/metrics
    deploy:
      mode: global