version: '3.8'
services:
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest # Sesuaikan versi
    privileged: true
    volumes:
      - /:/rootfs:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /run:/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /proc:/proc:ro
      - /cgroup:/cgroup:ro
    deploy:
      mode: global # cAdvisor berjalan di semua node Swarm

  collector:
    image: ${ACR_URL}/metrics-collector:${IMAGE_TAG}
    environment:
      - CADVISOR_URL=http://cadvisor:8080/api/v1.3/containers/
      - API_URL=https://aca-monitoring-api.politesea-d4b7dfa0.spaincentral.azurecontainerapps.io/metrics
    deploy:
      mode: global